apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: client-deployment
          image: dalihmida01/front:3
          ports:
            - containerPort: 80
